version: '3.8'

services:
  lilit-astro:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - API_KEY=1nqDQcl12AYZctUhuVxvroI2CrLuG4pW
    restart: unless-stopped 
