version: '3.8'

services:
  lilit-astro:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    env_file: .env
    restart: unless-stopped 
