name: 🔮 formatting

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black autoflake ruff

    - name: Format with black
      run: black --line-length 100 .

    - name: Check for unused imports with autoflake
      run: autoflake --check --recursive --remove-all-unused-imports .

    - name: Fix issues with ruff
      run: ruff check . --fix
